export const SAVE_POKEMONS = 'SAVE_POKEMONS'
export const SAVE_NEXT_URL = 'SAVE_NEXT_URL'
export const LOADED = 'LOADED'
export const GET_FILTER_TYPES = 'GET_FILTER_TYPES'
export const SET_FILTER = 'SET_FILTER'
export const REMOVE_FILTER = 'REMOVE_FILTER'
